//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace KEWIStudents.NAVWS {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Studentportal_Binding", Namespace="urn:microsoft-dynamics-schemas/codeunit/Studentportal")]
    public partial class Studentportal : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CheckPasswordChangedOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckValidStudentNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GenerateBillRefNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GenerateFeesStatementOperationCompleted;
        
        private System.Threading.SendOrPostCallback GenerateReceiptOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCourseRegistrationDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCurrentAcademicYearOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCurrentSemesterDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCurrentSemesterOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFeesStatementOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPaymentReceiptsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProgramNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStudentCourseDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStudentDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStudentFeesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStudentStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback HasUpdatedProfileOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsStudentRegisteredOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginForChangedPasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginForUnchangedPasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback SavePesaFlowInvoiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateStudentPasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateStudentProfileOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Studentportal() {
            this.Url = global::KEWIStudents.Properties.Settings.Default.KEWIStudents_NAVWS_Studentportal;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CheckPasswordChangedCompletedEventHandler CheckPasswordChangedCompleted;
        
        /// <remarks/>
        public event CheckValidStudentNoCompletedEventHandler CheckValidStudentNoCompleted;
        
        /// <remarks/>
        public event GenerateBillRefNoCompletedEventHandler GenerateBillRefNoCompleted;
        
        /// <remarks/>
        public event GenerateFeesStatementCompletedEventHandler GenerateFeesStatementCompleted;
        
        /// <remarks/>
        public event GenerateReceiptCompletedEventHandler GenerateReceiptCompleted;
        
        /// <remarks/>
        public event GetCourseRegistrationDataCompletedEventHandler GetCourseRegistrationDataCompleted;
        
        /// <remarks/>
        public event GetCurrentAcademicYearCompletedEventHandler GetCurrentAcademicYearCompleted;
        
        /// <remarks/>
        public event GetCurrentSemesterDetailsCompletedEventHandler GetCurrentSemesterDetailsCompleted;
        
        /// <remarks/>
        public event GetCurrentSemesterCompletedEventHandler GetCurrentSemesterCompleted;
        
        /// <remarks/>
        public event GetFeesStatementCompletedEventHandler GetFeesStatementCompleted;
        
        /// <remarks/>
        public event GetPaymentReceiptsCompletedEventHandler GetPaymentReceiptsCompleted;
        
        /// <remarks/>
        public event GetProgramNameCompletedEventHandler GetProgramNameCompleted;
        
        /// <remarks/>
        public event GetStudentCourseDataCompletedEventHandler GetStudentCourseDataCompleted;
        
        /// <remarks/>
        public event GetStudentDetailsCompletedEventHandler GetStudentDetailsCompleted;
        
        /// <remarks/>
        public event GetStudentFeesCompletedEventHandler GetStudentFeesCompleted;
        
        /// <remarks/>
        public event GetStudentStatusCompletedEventHandler GetStudentStatusCompleted;
        
        /// <remarks/>
        public event HasUpdatedProfileCompletedEventHandler HasUpdatedProfileCompleted;
        
        /// <remarks/>
        public event IsStudentRegisteredCompletedEventHandler IsStudentRegisteredCompleted;
        
        /// <remarks/>
        public event LoginForChangedPasswordCompletedEventHandler LoginForChangedPasswordCompleted;
        
        /// <remarks/>
        public event LoginForUnchangedPasswordCompletedEventHandler LoginForUnchangedPasswordCompleted;
        
        /// <remarks/>
        public event SavePesaFlowInvoiceCompletedEventHandler SavePesaFlowInvoiceCompleted;
        
        /// <remarks/>
        public event UpdateStudentPasswordCompletedEventHandler UpdateStudentPasswordCompleted;
        
        /// <remarks/>
        public event UpdateStudentProfileCompletedEventHandler UpdateStudentProfileCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Studentportal:CheckPasswordChanged", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Studentportal", ResponseElementName="CheckPasswordChanged_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Studentportal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool CheckPasswordChanged(string username) {
            object[] results = this.Invoke("CheckPasswordChanged", new object[] {
                        username});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CheckPasswordChangedAsync(string username) {
            this.CheckPasswordChangedAsync(username, null);
        }
        
        /// <remarks/>
        public void CheckPasswordChangedAsync(string username, object userState) {
            if ((this.CheckPasswordChangedOperationCompleted == null)) {
                this.CheckPasswordChangedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckPasswordChangedOperationCompleted);
            }
            this.InvokeAsync("CheckPasswordChanged", new object[] {
                        username}, this.CheckPasswordChangedOperationCompleted, userState);
        }
        
        private void OnCheckPasswordChangedOperationCompleted(object arg) {
            if ((this.CheckPasswordChangedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckPasswordChangedCompleted(this, new CheckPasswordChangedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Studentportal:CheckValidStudentNo", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Studentportal", ResponseElementName="CheckValidStudentNo_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Studentportal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CheckValidStudentNo(string username) {
            this.Invoke("CheckValidStudentNo", new object[] {
                        username});
        }
        
        /// <remarks/>
        public void CheckValidStudentNoAsync(string username) {
            this.CheckValidStudentNoAsync(username, null);
        }
        
        /// <remarks/>
        public void CheckValidStudentNoAsync(string username, object userState) {
            if ((this.CheckValidStudentNoOperationCompleted == null)) {
                this.CheckValidStudentNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckValidStudentNoOperationCompleted);
            }
            this.InvokeAsync("CheckValidStudentNo", new object[] {
                        username}, this.CheckValidStudentNoOperationCompleted, userState);
        }
        
        private void OnCheckValidStudentNoOperationCompleted(object arg) {
            if ((this.CheckValidStudentNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckValidStudentNoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Studentportal:GenerateBillRefNo", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Studentportal", ResponseElementName="GenerateBillRefNo_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Studentportal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GenerateBillRefNo() {
            object[] results = this.Invoke("GenerateBillRefNo", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GenerateBillRefNoAsync() {
            this.GenerateBillRefNoAsync(null);
        }
        
        /// <remarks/>
        public void GenerateBillRefNoAsync(object userState) {
            if ((this.GenerateBillRefNoOperationCompleted == null)) {
                this.GenerateBillRefNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerateBillRefNoOperationCompleted);
            }
            this.InvokeAsync("GenerateBillRefNo", new object[0], this.GenerateBillRefNoOperationCompleted, userState);
        }
        
        private void OnGenerateBillRefNoOperationCompleted(object arg) {
            if ((this.GenerateBillRefNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerateBillRefNoCompleted(this, new GenerateBillRefNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Studentportal:GenerateFeesStatement", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Studentportal", ResponseElementName="GenerateFeesStatement_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Studentportal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GenerateFeesStatement(string username, string fileNameFromApp) {
            this.Invoke("GenerateFeesStatement", new object[] {
                        username,
                        fileNameFromApp});
        }
        
        /// <remarks/>
        public void GenerateFeesStatementAsync(string username, string fileNameFromApp) {
            this.GenerateFeesStatementAsync(username, fileNameFromApp, null);
        }
        
        /// <remarks/>
        public void GenerateFeesStatementAsync(string username, string fileNameFromApp, object userState) {
            if ((this.GenerateFeesStatementOperationCompleted == null)) {
                this.GenerateFeesStatementOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerateFeesStatementOperationCompleted);
            }
            this.InvokeAsync("GenerateFeesStatement", new object[] {
                        username,
                        fileNameFromApp}, this.GenerateFeesStatementOperationCompleted, userState);
        }
        
        private void OnGenerateFeesStatementOperationCompleted(object arg) {
            if ((this.GenerateFeesStatementCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerateFeesStatementCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Studentportal:GenerateReceipt", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Studentportal", ResponseElementName="GenerateReceipt_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Studentportal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GenerateReceipt(string receiptNo, string fileNameFromApp) {
            this.Invoke("GenerateReceipt", new object[] {
                        receiptNo,
                        fileNameFromApp});
        }
        
        /// <remarks/>
        public void GenerateReceiptAsync(string receiptNo, string fileNameFromApp) {
            this.GenerateReceiptAsync(receiptNo, fileNameFromApp, null);
        }
        
        /// <remarks/>
        public void GenerateReceiptAsync(string receiptNo, string fileNameFromApp, object userState) {
            if ((this.GenerateReceiptOperationCompleted == null)) {
                this.GenerateReceiptOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerateReceiptOperationCompleted);
            }
            this.InvokeAsync("GenerateReceipt", new object[] {
                        receiptNo,
                        fileNameFromApp}, this.GenerateReceiptOperationCompleted, userState);
        }
        
        private void OnGenerateReceiptOperationCompleted(object arg) {
            if ((this.GenerateReceiptCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerateReceiptCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Studentportal:GetCourseRegistrationData", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Studentportal", ResponseElementName="GetCourseRegistrationData_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Studentportal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetCourseRegistrationData(string username) {
            object[] results = this.Invoke("GetCourseRegistrationData", new object[] {
                        username});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCourseRegistrationDataAsync(string username) {
            this.GetCourseRegistrationDataAsync(username, null);
        }
        
        /// <remarks/>
        public void GetCourseRegistrationDataAsync(string username, object userState) {
            if ((this.GetCourseRegistrationDataOperationCompleted == null)) {
                this.GetCourseRegistrationDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCourseRegistrationDataOperationCompleted);
            }
            this.InvokeAsync("GetCourseRegistrationData", new object[] {
                        username}, this.GetCourseRegistrationDataOperationCompleted, userState);
        }
        
        private void OnGetCourseRegistrationDataOperationCompleted(object arg) {
            if ((this.GetCourseRegistrationDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCourseRegistrationDataCompleted(this, new GetCourseRegistrationDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Studentportal:GetCurrentAcademicYear", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Studentportal", ResponseElementName="GetCurrentAcademicYear_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Studentportal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetCurrentAcademicYear() {
            object[] results = this.Invoke("GetCurrentAcademicYear", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCurrentAcademicYearAsync() {
            this.GetCurrentAcademicYearAsync(null);
        }
        
        /// <remarks/>
        public void GetCurrentAcademicYearAsync(object userState) {
            if ((this.GetCurrentAcademicYearOperationCompleted == null)) {
                this.GetCurrentAcademicYearOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCurrentAcademicYearOperationCompleted);
            }
            this.InvokeAsync("GetCurrentAcademicYear", new object[0], this.GetCurrentAcademicYearOperationCompleted, userState);
        }
        
        private void OnGetCurrentAcademicYearOperationCompleted(object arg) {
            if ((this.GetCurrentAcademicYearCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCurrentAcademicYearCompleted(this, new GetCurrentAcademicYearCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Studentportal:GetCurrentSemesterDetails", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Studentportal", ResponseElementName="GetCurrentSemesterDetails_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Studentportal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetCurrentSemesterDetails() {
            object[] results = this.Invoke("GetCurrentSemesterDetails", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCurrentSemesterDetailsAsync() {
            this.GetCurrentSemesterDetailsAsync(null);
        }
        
        /// <remarks/>
        public void GetCurrentSemesterDetailsAsync(object userState) {
            if ((this.GetCurrentSemesterDetailsOperationCompleted == null)) {
                this.GetCurrentSemesterDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCurrentSemesterDetailsOperationCompleted);
            }
            this.InvokeAsync("GetCurrentSemesterDetails", new object[0], this.GetCurrentSemesterDetailsOperationCompleted, userState);
        }
        
        private void OnGetCurrentSemesterDetailsOperationCompleted(object arg) {
            if ((this.GetCurrentSemesterDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCurrentSemesterDetailsCompleted(this, new GetCurrentSemesterDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Studentportal:GetCurrentSemester", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Studentportal", ResponseElementName="GetCurrentSemester_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Studentportal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetCurrentSemester() {
            object[] results = this.Invoke("GetCurrentSemester", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCurrentSemesterAsync() {
            this.GetCurrentSemesterAsync(null);
        }
        
        /// <remarks/>
        public void GetCurrentSemesterAsync(object userState) {
            if ((this.GetCurrentSemesterOperationCompleted == null)) {
                this.GetCurrentSemesterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCurrentSemesterOperationCompleted);
            }
            this.InvokeAsync("GetCurrentSemester", new object[0], this.GetCurrentSemesterOperationCompleted, userState);
        }
        
        private void OnGetCurrentSemesterOperationCompleted(object arg) {
            if ((this.GetCurrentSemesterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCurrentSemesterCompleted(this, new GetCurrentSemesterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Studentportal:GetFeesStatement", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Studentportal", ResponseElementName="GetFeesStatement_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Studentportal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetFeesStatement(string studentNo) {
            object[] results = this.Invoke("GetFeesStatement", new object[] {
                        studentNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetFeesStatementAsync(string studentNo) {
            this.GetFeesStatementAsync(studentNo, null);
        }
        
        /// <remarks/>
        public void GetFeesStatementAsync(string studentNo, object userState) {
            if ((this.GetFeesStatementOperationCompleted == null)) {
                this.GetFeesStatementOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFeesStatementOperationCompleted);
            }
            this.InvokeAsync("GetFeesStatement", new object[] {
                        studentNo}, this.GetFeesStatementOperationCompleted, userState);
        }
        
        private void OnGetFeesStatementOperationCompleted(object arg) {
            if ((this.GetFeesStatementCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFeesStatementCompleted(this, new GetFeesStatementCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Studentportal:GetPaymentReceipts", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Studentportal", ResponseElementName="GetPaymentReceipts_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Studentportal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetPaymentReceipts(string studentNo) {
            object[] results = this.Invoke("GetPaymentReceipts", new object[] {
                        studentNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetPaymentReceiptsAsync(string studentNo) {
            this.GetPaymentReceiptsAsync(studentNo, null);
        }
        
        /// <remarks/>
        public void GetPaymentReceiptsAsync(string studentNo, object userState) {
            if ((this.GetPaymentReceiptsOperationCompleted == null)) {
                this.GetPaymentReceiptsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPaymentReceiptsOperationCompleted);
            }
            this.InvokeAsync("GetPaymentReceipts", new object[] {
                        studentNo}, this.GetPaymentReceiptsOperationCompleted, userState);
        }
        
        private void OnGetPaymentReceiptsOperationCompleted(object arg) {
            if ((this.GetPaymentReceiptsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPaymentReceiptsCompleted(this, new GetPaymentReceiptsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Studentportal:GetProgramName", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Studentportal", ResponseElementName="GetProgramName_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Studentportal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetProgramName(string progId) {
            object[] results = this.Invoke("GetProgramName", new object[] {
                        progId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetProgramNameAsync(string progId) {
            this.GetProgramNameAsync(progId, null);
        }
        
        /// <remarks/>
        public void GetProgramNameAsync(string progId, object userState) {
            if ((this.GetProgramNameOperationCompleted == null)) {
                this.GetProgramNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProgramNameOperationCompleted);
            }
            this.InvokeAsync("GetProgramName", new object[] {
                        progId}, this.GetProgramNameOperationCompleted, userState);
        }
        
        private void OnGetProgramNameOperationCompleted(object arg) {
            if ((this.GetProgramNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProgramNameCompleted(this, new GetProgramNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Studentportal:GetStudentCourseData", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Studentportal", ResponseElementName="GetStudentCourseData_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Studentportal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetStudentCourseData(string studentNo) {
            object[] results = this.Invoke("GetStudentCourseData", new object[] {
                        studentNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetStudentCourseDataAsync(string studentNo) {
            this.GetStudentCourseDataAsync(studentNo, null);
        }
        
        /// <remarks/>
        public void GetStudentCourseDataAsync(string studentNo, object userState) {
            if ((this.GetStudentCourseDataOperationCompleted == null)) {
                this.GetStudentCourseDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStudentCourseDataOperationCompleted);
            }
            this.InvokeAsync("GetStudentCourseData", new object[] {
                        studentNo}, this.GetStudentCourseDataOperationCompleted, userState);
        }
        
        private void OnGetStudentCourseDataOperationCompleted(object arg) {
            if ((this.GetStudentCourseDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStudentCourseDataCompleted(this, new GetStudentCourseDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Studentportal:GetStudentDetails", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Studentportal", ResponseElementName="GetStudentDetails_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Studentportal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetStudentDetails(string username) {
            object[] results = this.Invoke("GetStudentDetails", new object[] {
                        username});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetStudentDetailsAsync(string username) {
            this.GetStudentDetailsAsync(username, null);
        }
        
        /// <remarks/>
        public void GetStudentDetailsAsync(string username, object userState) {
            if ((this.GetStudentDetailsOperationCompleted == null)) {
                this.GetStudentDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStudentDetailsOperationCompleted);
            }
            this.InvokeAsync("GetStudentDetails", new object[] {
                        username}, this.GetStudentDetailsOperationCompleted, userState);
        }
        
        private void OnGetStudentDetailsOperationCompleted(object arg) {
            if ((this.GetStudentDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStudentDetailsCompleted(this, new GetStudentDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Studentportal:GetStudentFees", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Studentportal", ResponseElementName="GetStudentFees_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Studentportal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetStudentFees(string username) {
            object[] results = this.Invoke("GetStudentFees", new object[] {
                        username});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetStudentFeesAsync(string username) {
            this.GetStudentFeesAsync(username, null);
        }
        
        /// <remarks/>
        public void GetStudentFeesAsync(string username, object userState) {
            if ((this.GetStudentFeesOperationCompleted == null)) {
                this.GetStudentFeesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStudentFeesOperationCompleted);
            }
            this.InvokeAsync("GetStudentFees", new object[] {
                        username}, this.GetStudentFeesOperationCompleted, userState);
        }
        
        private void OnGetStudentFeesOperationCompleted(object arg) {
            if ((this.GetStudentFeesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStudentFeesCompleted(this, new GetStudentFeesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Studentportal:GetStudentStatus", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Studentportal", ResponseElementName="GetStudentStatus_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Studentportal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetStudentStatus(string username) {
            object[] results = this.Invoke("GetStudentStatus", new object[] {
                        username});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetStudentStatusAsync(string username) {
            this.GetStudentStatusAsync(username, null);
        }
        
        /// <remarks/>
        public void GetStudentStatusAsync(string username, object userState) {
            if ((this.GetStudentStatusOperationCompleted == null)) {
                this.GetStudentStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStudentStatusOperationCompleted);
            }
            this.InvokeAsync("GetStudentStatus", new object[] {
                        username}, this.GetStudentStatusOperationCompleted, userState);
        }
        
        private void OnGetStudentStatusOperationCompleted(object arg) {
            if ((this.GetStudentStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStudentStatusCompleted(this, new GetStudentStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Studentportal:HasUpdatedProfile", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Studentportal", ResponseElementName="HasUpdatedProfile_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Studentportal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool HasUpdatedProfile(string username) {
            object[] results = this.Invoke("HasUpdatedProfile", new object[] {
                        username});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void HasUpdatedProfileAsync(string username) {
            this.HasUpdatedProfileAsync(username, null);
        }
        
        /// <remarks/>
        public void HasUpdatedProfileAsync(string username, object userState) {
            if ((this.HasUpdatedProfileOperationCompleted == null)) {
                this.HasUpdatedProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHasUpdatedProfileOperationCompleted);
            }
            this.InvokeAsync("HasUpdatedProfile", new object[] {
                        username}, this.HasUpdatedProfileOperationCompleted, userState);
        }
        
        private void OnHasUpdatedProfileOperationCompleted(object arg) {
            if ((this.HasUpdatedProfileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HasUpdatedProfileCompleted(this, new HasUpdatedProfileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Studentportal:IsStudentRegistered", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Studentportal", ResponseElementName="IsStudentRegistered_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Studentportal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool IsStudentRegistered(string studentNo) {
            object[] results = this.Invoke("IsStudentRegistered", new object[] {
                        studentNo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsStudentRegisteredAsync(string studentNo) {
            this.IsStudentRegisteredAsync(studentNo, null);
        }
        
        /// <remarks/>
        public void IsStudentRegisteredAsync(string studentNo, object userState) {
            if ((this.IsStudentRegisteredOperationCompleted == null)) {
                this.IsStudentRegisteredOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsStudentRegisteredOperationCompleted);
            }
            this.InvokeAsync("IsStudentRegistered", new object[] {
                        studentNo}, this.IsStudentRegisteredOperationCompleted, userState);
        }
        
        private void OnIsStudentRegisteredOperationCompleted(object arg) {
            if ((this.IsStudentRegisteredCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsStudentRegisteredCompleted(this, new IsStudentRegisteredCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Studentportal:LoginForChangedPassword", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Studentportal", ResponseElementName="LoginForChangedPassword_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Studentportal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string LoginForChangedPassword(string username, string password) {
            object[] results = this.Invoke("LoginForChangedPassword", new object[] {
                        username,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LoginForChangedPasswordAsync(string username, string password) {
            this.LoginForChangedPasswordAsync(username, password, null);
        }
        
        /// <remarks/>
        public void LoginForChangedPasswordAsync(string username, string password, object userState) {
            if ((this.LoginForChangedPasswordOperationCompleted == null)) {
                this.LoginForChangedPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginForChangedPasswordOperationCompleted);
            }
            this.InvokeAsync("LoginForChangedPassword", new object[] {
                        username,
                        password}, this.LoginForChangedPasswordOperationCompleted, userState);
        }
        
        private void OnLoginForChangedPasswordOperationCompleted(object arg) {
            if ((this.LoginForChangedPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginForChangedPasswordCompleted(this, new LoginForChangedPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Studentportal:LoginForUnchangedPassword", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Studentportal", ResponseElementName="LoginForUnchangedPassword_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Studentportal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string LoginForUnchangedPassword(string username) {
            object[] results = this.Invoke("LoginForUnchangedPassword", new object[] {
                        username});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LoginForUnchangedPasswordAsync(string username) {
            this.LoginForUnchangedPasswordAsync(username, null);
        }
        
        /// <remarks/>
        public void LoginForUnchangedPasswordAsync(string username, object userState) {
            if ((this.LoginForUnchangedPasswordOperationCompleted == null)) {
                this.LoginForUnchangedPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginForUnchangedPasswordOperationCompleted);
            }
            this.InvokeAsync("LoginForUnchangedPassword", new object[] {
                        username}, this.LoginForUnchangedPasswordOperationCompleted, userState);
        }
        
        private void OnLoginForUnchangedPasswordOperationCompleted(object arg) {
            if ((this.LoginForUnchangedPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginForUnchangedPasswordCompleted(this, new LoginForUnchangedPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Studentportal:SavePesaFlowInvoice", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Studentportal", ResponseElementName="SavePesaFlowInvoice_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Studentportal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool SavePesaFlowInvoice(string refno, string invoiceno, string custno, string custname, decimal invoiceamt, string serviceid, string desc, string token, string link) {
            object[] results = this.Invoke("SavePesaFlowInvoice", new object[] {
                        refno,
                        invoiceno,
                        custno,
                        custname,
                        invoiceamt,
                        serviceid,
                        desc,
                        token,
                        link});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SavePesaFlowInvoiceAsync(string refno, string invoiceno, string custno, string custname, decimal invoiceamt, string serviceid, string desc, string token, string link) {
            this.SavePesaFlowInvoiceAsync(refno, invoiceno, custno, custname, invoiceamt, serviceid, desc, token, link, null);
        }
        
        /// <remarks/>
        public void SavePesaFlowInvoiceAsync(string refno, string invoiceno, string custno, string custname, decimal invoiceamt, string serviceid, string desc, string token, string link, object userState) {
            if ((this.SavePesaFlowInvoiceOperationCompleted == null)) {
                this.SavePesaFlowInvoiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSavePesaFlowInvoiceOperationCompleted);
            }
            this.InvokeAsync("SavePesaFlowInvoice", new object[] {
                        refno,
                        invoiceno,
                        custno,
                        custname,
                        invoiceamt,
                        serviceid,
                        desc,
                        token,
                        link}, this.SavePesaFlowInvoiceOperationCompleted, userState);
        }
        
        private void OnSavePesaFlowInvoiceOperationCompleted(object arg) {
            if ((this.SavePesaFlowInvoiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SavePesaFlowInvoiceCompleted(this, new SavePesaFlowInvoiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Studentportal:UpdateStudentPassword", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Studentportal", ResponseElementName="UpdateStudentPassword_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Studentportal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateStudentPassword(string username, string genpass) {
            this.Invoke("UpdateStudentPassword", new object[] {
                        username,
                        genpass});
        }
        
        /// <remarks/>
        public void UpdateStudentPasswordAsync(string username, string genpass) {
            this.UpdateStudentPasswordAsync(username, genpass, null);
        }
        
        /// <remarks/>
        public void UpdateStudentPasswordAsync(string username, string genpass, object userState) {
            if ((this.UpdateStudentPasswordOperationCompleted == null)) {
                this.UpdateStudentPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateStudentPasswordOperationCompleted);
            }
            this.InvokeAsync("UpdateStudentPassword", new object[] {
                        username,
                        genpass}, this.UpdateStudentPasswordOperationCompleted, userState);
        }
        
        private void OnUpdateStudentPasswordOperationCompleted(object arg) {
            if ((this.UpdateStudentPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateStudentPasswordCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Studentportal:UpdateStudentProfile", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Studentportal", ResponseElementName="UpdateStudentProfile_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Studentportal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateStudentProfile(string username, string idNumber, string phoneNo, string email, int gender, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime dob, string county, string tribe, int disability, string disabilityDescription) {
            this.Invoke("UpdateStudentProfile", new object[] {
                        username,
                        idNumber,
                        phoneNo,
                        email,
                        gender,
                        dob,
                        county,
                        tribe,
                        disability,
                        disabilityDescription});
        }
        
        /// <remarks/>
        public void UpdateStudentProfileAsync(string username, string idNumber, string phoneNo, string email, int gender, System.DateTime dob, string county, string tribe, int disability, string disabilityDescription) {
            this.UpdateStudentProfileAsync(username, idNumber, phoneNo, email, gender, dob, county, tribe, disability, disabilityDescription, null);
        }
        
        /// <remarks/>
        public void UpdateStudentProfileAsync(string username, string idNumber, string phoneNo, string email, int gender, System.DateTime dob, string county, string tribe, int disability, string disabilityDescription, object userState) {
            if ((this.UpdateStudentProfileOperationCompleted == null)) {
                this.UpdateStudentProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateStudentProfileOperationCompleted);
            }
            this.InvokeAsync("UpdateStudentProfile", new object[] {
                        username,
                        idNumber,
                        phoneNo,
                        email,
                        gender,
                        dob,
                        county,
                        tribe,
                        disability,
                        disabilityDescription}, this.UpdateStudentProfileOperationCompleted, userState);
        }
        
        private void OnUpdateStudentProfileOperationCompleted(object arg) {
            if ((this.UpdateStudentProfileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateStudentProfileCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void CheckPasswordChangedCompletedEventHandler(object sender, CheckPasswordChangedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckPasswordChangedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckPasswordChangedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void CheckValidStudentNoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GenerateBillRefNoCompletedEventHandler(object sender, GenerateBillRefNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GenerateBillRefNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GenerateBillRefNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GenerateFeesStatementCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GenerateReceiptCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetCourseRegistrationDataCompletedEventHandler(object sender, GetCourseRegistrationDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCourseRegistrationDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCourseRegistrationDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetCurrentAcademicYearCompletedEventHandler(object sender, GetCurrentAcademicYearCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCurrentAcademicYearCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCurrentAcademicYearCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetCurrentSemesterDetailsCompletedEventHandler(object sender, GetCurrentSemesterDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCurrentSemesterDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCurrentSemesterDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetCurrentSemesterCompletedEventHandler(object sender, GetCurrentSemesterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCurrentSemesterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCurrentSemesterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetFeesStatementCompletedEventHandler(object sender, GetFeesStatementCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFeesStatementCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFeesStatementCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetPaymentReceiptsCompletedEventHandler(object sender, GetPaymentReceiptsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPaymentReceiptsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPaymentReceiptsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetProgramNameCompletedEventHandler(object sender, GetProgramNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProgramNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProgramNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetStudentCourseDataCompletedEventHandler(object sender, GetStudentCourseDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStudentCourseDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStudentCourseDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetStudentDetailsCompletedEventHandler(object sender, GetStudentDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStudentDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStudentDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetStudentFeesCompletedEventHandler(object sender, GetStudentFeesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStudentFeesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStudentFeesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetStudentStatusCompletedEventHandler(object sender, GetStudentStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStudentStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStudentStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void HasUpdatedProfileCompletedEventHandler(object sender, HasUpdatedProfileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HasUpdatedProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HasUpdatedProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void IsStudentRegisteredCompletedEventHandler(object sender, IsStudentRegisteredCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsStudentRegisteredCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsStudentRegisteredCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void LoginForChangedPasswordCompletedEventHandler(object sender, LoginForChangedPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginForChangedPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginForChangedPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void LoginForUnchangedPasswordCompletedEventHandler(object sender, LoginForUnchangedPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginForUnchangedPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginForUnchangedPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void SavePesaFlowInvoiceCompletedEventHandler(object sender, SavePesaFlowInvoiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SavePesaFlowInvoiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SavePesaFlowInvoiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void UpdateStudentPasswordCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void UpdateStudentProfileCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591